### ISSUE TITLE
ImportError after installation

### ISSUE THREAD

**Issue by williamn** [eatonphil/spinup#1]
This is an interesting work. Thanks.

Here is my problem.

I have installed vhostm by running:

`sudo -H pip install vhost`

But when I start to use it I got ImportError like below:

```
Traceback (most recent call last):
  File "/usr/local/bin/vhostm", line 7, in <module>
    from vhostm.vhostm import main
ImportError: No module named vhostm.vhostm
```

**Comment by eatonphil** [comment]
What version of python are you running?

**Comment by williamn** [comment]
Ah my bad. I missed the text that said this for Python 3. I use 2.7

**Comment by eatonphil** [comment]
Yep. If you want to try to make it backwards compatible, feel free to submit a PR and we'll take a look. Otherwise you can just also install python3 and [get-pip](https://bootstrap.pypa.io/get-pip.py) and use pip3(.5) to install the package.
